### PR TITLE
Update main.py

### LINKED ISSUE #16: main.py very informal message
Hey @shajin-sha I think that [this](https://github.com/bionic-py/Bionic/blob/108f3a7b276f643f9e832aabc73b5bb04bf96462/Bionic/main.py#L9) message is not very informal message. I think it will be better to write a nice message, like `Hi There 👋, thanks for trying out bionic. We the team of Bionic wish you a very happy development with Bionic.`

### PR DESCRIPTION
**Pull request by TarunavBA**
### What I have done,
- I have added a more good 👍 message in the line 9,
- I have added the call for the ```def RunApp()``` in line 12

### CODE REVIEW

**Comment by TarunavBA** [comment]
Hey @shajin-sha can you please let me know if we could still merge this PR? Please let me know as soon as possible so that I can close this if this PR couldn't be merged.

**Review by shajin-sha — APPROVED** [review]
Okey👍🏻👍🏻

**Comment by TarunavBA** [comment]
So @shajin-sha should i close this issue?

**Comment by TarunavBA** [comment]
As no reply has come for me to go on I'm closing this issue for now.

**Review by shajin-sha — APPROVED** [review]

**Comment by shajin-sha** [comment]
> So @shajin-sha should i close this issue? 

Nop

**Pull request closed without merging**
