### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TarunavBA**
### What I have done 
---
- Added extra words in line 38
- called the `RunApp()` function in line 55

### CODE REVIEW

**Comment by shajin-sha** [comment]
> Hey no need to change main.py (this is jest a template)

> A good template is loading

> No need to call that function as for this called in side of bionic.py


👍🏻

**Review by shajin-sha — APPROVED** [review]
Cool

**Comment by TarunavBA** [comment]
Hey @shaji-sha now I have removed the `RunApp()` command, check if you can merge it.

**Review by shajin-sha — APPROVED** [review]
Great

**Pull request merged**
